name = "url-analyzer"
main = "src/index.ts"
compatibility_date = "2023-10-30"

# AI binding
[[ai_binding]]
binding = "AI"
service = "@cf/meta/llama-3-8b-instruct"

# Environment variables
# [vars]
# This is just a placeholder - set the actual key in the Cloudflare dashboard
# API_KEY = "your-api-key-placeholder"
