name = "url-analyzer"
main = "src/index.ts"
compatibility_date = "2025-04-19"

# AI binding
[ai]
binding = "AI"

# Environment variables
# [vars]
# This is just a placeholder - set the actual key in the Cloudflare dashboard
# API_KEY = "your-api-key-placeholder"
